### ISSUE TITLE
Gradle build keeps failing

### ISSUE THREAD

**Issue by zennur** [ConsenSys/gpact#6]
I installed all the requirements listed and added Web3J to the gpact folder. But I keep getting this when I am trying the `scripts/create_chain.js 32 1` command:
```
~/gpact$ scripts/create_chain.js 32 1
Creating a blockchain with chainID 32 and 1 validators in the genesis file...
child_process.js:661
    throw err;
    ^

<ref *1> Error: spawnSync ../besu/build/install/besu/bin/besu ENOENT
    at Object.spawnSync (internal/child_process.js:1074:20)
    at spawnSync (child_process.js:626:24)
    at execFileSync (child_process.js:653:15)
    at Object.<anonymous> (/home/user/gpact/scripts/create_chain.js:79:17)
    at Module._compile (internal/modules/cjs/loader.js:1068:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1097:10)
    at Module.load (internal/modules/cjs/loader.js:933:32)
    at Function.Module._load (internal/modules/cjs/loader.js:774:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawnSync ../besu/build/install/besu/bin/besu',
  path: '../besu/build/install/besu/bin/besu',
  spawnargs: [
    '--data-path=/home/user/cgpact_data/chain32/node0',
    'public-key',
    'export-address',
    '--to=/home/user/cgpact_data/chain32/node0/node-acct'
  ],
  error: [Circular *1],
  status: null,
  signal: null,
  output: null,
  pid: 43928,
  stdout: null,
  stderr: null
}

```

What would be the potential reason to that? I am sorry if this is an obvious question, I'm new in this.

**Comment by drinkcoffee** [comment]
Hello @zennur , sorry, I just saw this. The blockchain creation now uses Docker. As such, this issue you see above no longer exists.
